name: build-swarm

on:
  schedule:
    - cron: '0 0 * * 1'

  push:
    branches:
      - 'main'

  workflow_dispatch:
  
jobs:
  
  test:
    uses: ./.github/workflows/test.yml
    with:
      # The Dockerfile to build
      dockerfile: Dockerfile
      dockerfile_folder: build
      image_name: helix-swarm
      version: 2024.5
    secrets: inherit

  push:
    uses: ./.github/workflows/publish.yml
    needs: test
    with:
      # The Dockerfile to build
      dockerfile: Dockerfile
      dockerfile_folder: build
      image_name: helix-swarm
      version: 2024.5
    secrets: inherit
